layout_spectrum: 0.9981343
typography_spectrum: 0.2397388
color:
  saturation: 0.9407649
  lightness: 0.05083955
  brandStrength: 0
  brandColors:
    - '#383732'
    - '#707478'
    - '#9EC074'
    - '#7C7000'
    - '#FA9B2B'
  rhythmicContrast: 0.04214103
name: Steve Levinsky Glass Art
